### ISSUE TITLE
Option to add import paths

### ISSUE THREAD

**Issue by devin-QB** [Dancheg97/grpclicker_vscode#126]
We need an option to specify import paths, which can be used to resolve "import" directives in .proto files

**Comment by Dancheg97** [comment]
You can specify path for imports, when you add new file using `plus`:


![image](https://user-images.githubusercontent.com/58640116/193460396-81481cdf-3da4-4dc2-968f-67929e830c99.png)


![image](https://user-images.githubusercontent.com/58640116/193460360-c736308e-57fd-40f6-aa9a-a148020b70f8.png)

**Comment by devin-QB** [comment]
Using that I can only specify one import path. but I have multiple import paths.

**Comment by Dancheg97** [comment]
There is option to specify additional custom flags for each proto source in new release, check if this fits your needs
