### ISSUE TITLE
Context deadline exceeded (-max-time)

### ISSUE THREAD

**Issue by DaxCax** [Dancheg97/grpclicker_vscode#127]
Trying to add a reflect server but getting this error about deadline. Tried the **grpcurl** from command line and raised _-max-time_ to 3. Then it worked fine.
Max-time seems hard coded. Possible solutions?

**Comment by DaxCax** [comment]
Temporary change in _extension.js_ worked.

**Comment by Dancheg97** [comment]
Sure, will move this option to settings

**Comment by Dancheg97** [comment]
Will be added to next release, you can now set timeout for reflect servers in settings:
![image](https://user-images.githubusercontent.com/58640116/200006919-8dccfbe0-b875-4269-ab2a-3b79aa5ce4b8.png)

**Comment by DaxCax** [comment]
Great 👍
Possible to make a new release to VSCode marketplace? Trying to introduce this extension to the rest of the team.

**Comment by Dancheg97** [comment]
updating:
![image](https://user-images.githubusercontent.com/58640116/202711928-d3e97a6d-a566-48e2-94ec-7e16fede8c98.png)
