### ISSUE TITLE
The uniqueness of the window is determined only by the name of the handler, but not by the endpoint address

### ISSUE THREAD

**Issue by n-r-w** [Dancheg97/grpclicker_vscode#134]
If it is necessary to compare two instances of the same service (with the same handler names), then the extension does not distinguish one from the other. 
For example, if a window with handler call parameters "service1.handler1" is already open, and then open the window "service 2.handler1", then instead of opening a new window, the window "service1.handler1" will simply open.
![image](https://user-images.githubusercontent.com/38435980/232056405-f60216b5-2e5c-4490-b41c-847edd0bc210.png)

**Comment by Dancheg97** [comment]
Got it, will release a fix soon.

**Comment by Dancheg97** [comment]
fixed
